# .streamlit/config.toml

[theme]
# primaryColor="#F63366"
# backgroundColor="#FFFFFF"
# secondaryBackgroundColor="#F0F2F6"
# textColor="#262730"
# font="sans serif"

[server]
# headless = true # Already set by ENV var in Dockerfile
# enableCORS = false # Already default
# enableXsrfProtection = true # Already set by ENV var

[logger]
# Level for Streamlit's own logger, not your app's logger
# level = "info" 

[browser]
gatherUsageStats = false
